spring.application.name=E-commerce

# ==============================================================
# == DATABASE CONFIGURATION                                  ==
# ==============================================================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================================================
# == JPA / HIBERNATE SETTINGS (For MySQL)                    ==
# ==============================================================
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Logging
logging.level.com.example.ecommerce=DEBUG
logging.level.org.springframework.web=INFO


# ==============================================================
# == JWT CONFIGURATION                                       ==
# ==============================================================
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.cookie-expiration=864000000
app.jwt.expiration-ms=864000000
app.jwt.refresh-expiration=864000000